// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOI4FeMWl7bwfu322Dj1uyuZbvKT7qfTo',
    appId: '1:932534568815:web:3e7a8fe28da55a7bb44a9a',
    messagingSenderId: '932534568815',
    projectId: 'loratest-76a91',
    authDomain: 'loratest-76a91.firebaseapp.com',
    databaseURL: 'https://loratest-76a91-default-rtdb.firebaseio.com',
    storageBucket: 'loratest-76a91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOI4FeMWl7bwfu322Dj1uyuZbvKT7qfTo',
    appId: '1:932534568815:android:3e7a8fe28da55a7bb44a9a',
    messagingSenderId: '932534568815',
    projectId: 'loratest-76a91',
    databaseURL: 'https://loratest-76a91-default-rtdb.firebaseio.com',
    storageBucket: 'loratest-76a91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOI4FeMWl7bwfu322Dj1uyuZbvKT7qfTo',
    appId: '1:932534568815:ios:3e7a8fe28da55a7bb44a9a',
    messagingSenderId: '932534568815',
    projectId: 'loratest-76a91',
    databaseURL: 'https://loratest-76a91-default-rtdb.firebaseio.com',
    storageBucket: 'loratest-76a91.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Replace with actual iOS client ID if available
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOI4FeMWl7bwfu322Dj1uyuZbvKT7qfTo',
    appId: '1:932534568815:macos:3e7a8fe28da55a7bb44a9a',
    messagingSenderId: '932534568815',
    projectId: 'loratest-76a91',
    databaseURL: 'https://loratest-76a91-default-rtdb.firebaseio.com',
    storageBucket: 'loratest-76a91.firebasestorage.app',
    iosClientId: 'YOUR_MACOS_CLIENT_ID', // Replace with actual macOS client ID if available
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOI4FeMWl7bwfu322Dj1uyuZbvKT7qfTo',
    appId: '1:932534568815:windows:3e7a8fe28da55a7bb44a9a',
    messagingSenderId: '932534568815',
    projectId: 'loratest-76a91',
    databaseURL: 'https://loratest-76a91-default-rtdb.firebaseio.com',
    storageBucket: 'loratest-76a91.firebasestorage.app',
  );
} 